export const siteConfig = {
  name: 'CricketScoreHQ',
  shortName: 'CricketScoreHQ',
  title: 'CricketScoreHQ — Live Cricket Scores, Fixtures, Stats, Match Previews & News',
  description:
    'Live cricket scores, ball-by-ball commentary, fixtures, player statistics, match previews, reviews and latest cricket news from international and franchise cricket worldwide.',
  url: 'https://cricketscorehq.com',
  ogImage: '/og-image.png',
  twitter: '@cricketscorehq',
  keywords: [
    'cricket scores',
    'live cricket score',
    'cricket fixtures',
    'cricket schedule',
    'cricket player stats',
    'cricket match preview',
    'cricket news',
    'cricket updates',
    'cricket commentary',
    'international cricket',
    'ipl scores',
    'bbl scores',
    'psl scores',
    'test cricket',
    'odi cricket',
    't20 cricket',
    'cricket rankings',
    'cricket records',
    'cricket teams',
    'cricket tournaments',
  ],
  author: {
    name: 'CricketScoreHQ Editorial Team',
    url: 'https://cricketscorehq.com/about',
  },
  contact: {
    email: 'editorial@cricketscorehq.com',
    twitter: '@cricketscorehq',
  },
  social: {
    twitter: 'https://twitter.com/cricketscorehq',
    youtube: 'https://youtube.com/@cricketscorehq',
    instagram: 'https://instagram.com/cricketscorehq',
    facebook: 'https://facebook.com/cricketscorehq',
  },
  nav: [
    { name: 'Home', href: '/' },
    { name: 'Live Scores', href: '/live-scores' },
    { name: 'Fixtures', href: '/fixtures' },
    { name: 'Series', href: '/series' },
    { name: 'Teams', href: '/teams' },
    { name: 'Players', href: '/players' },
    { name: 'Rankings', href: '/rankings' },
    { name: 'News', href: '/news' },
    { name: 'Blog', href: '/blog' },
    { name: 'About', href: '/about' },
    { name: 'Contact', href: '/contact' },
  ],
  legalNav: [
    { name: 'Disclaimer', href: '/disclaimer' },
    { name: 'Privacy Policy', href: '/privacy-policy' },
    { name: 'Terms of Use', href: '/terms' },
    { name: 'Editorial Policy', href: '/editorial-policy' },
    { name: 'Fact-Checking Policy', href: '/fact-checking-policy' },
  ],
};

export type NavItem = { name: string; href: string };
